---
title: "SPQ Data Plots"
output: html_document
date: "2023-04-11"
---

```{r}
library("dplyr")
library("ggplot2")
library("tidyr")
library("vegan")
library("tibble")
library("ggpubr")
library("lme4")
library("sjPlot")
```

# Load Data
```{r}
data <- read.csv("../data/annotations.csv")

load("../../bruvs/data/created/mean.sum.shark.abundance.tiles.RData") # mean.shark.abundance.tiles

load(file = "../../dovs/data/created/fish.site.tiles.average.RData") # fish.site.tiles.average

load("../../grazing/data/bite.data.RData") # herbivore.bites.site
```



# Data Wrangling
```{r}
### WIDE DF ####
test <- data %>%
  group_by(Atoll, Site, Transect,Quadrat) %>%
  count(Label)

test <- as.data.frame(test)

test$Site.Transect.Quadrat <- paste(test$Site,test$Transect, test$Quadrat, sep=".")


benthic.wide <- test %>% 
  pivot_wider(names_from = Label, 
              values_from = n, 
              values_fill = 0)
dim(benthic.wide) # 240 quadrats (30 X 8 sites)



# Filter out cover categories we don't want to include
benthic.wide.clean <- benthic.wide %>%
  dplyr::select(-c("*TAPE", "PVC", "OOQ", "MOBL")) 


# Normalize by number of points
df1 <- benthic.wide.clean %>% 
  column_to_rownames(var="Site.Transect.Quadrat")%>% 
  dplyr::select(c("*CCAH":"OTH-SINV"))
rowSums(df1) # all close to 50

df2 <- decostand(df1, "total") 
rowSums(df2) # 1
# this creates a df with normalized cover categories

# add back normalized data
meta <- benthic.wide.clean %>%
  select(c(Atoll:Site.Transect.Quadrat))

benthic_wide <- df2 %>%
  rownames_to_column("Site.Transect.Quadrat") %>%
  left_join(meta, by="Site.Transect.Quadrat") %>%
  select(c(Atoll:Quadrat), Site.Transect.Quadrat, "*CCAH":"OTH-SINV") %>%
  # Rename and group the categories
  mutate("CCA"= `*CCAH` + `*CCAR`) %>%
  mutate("Macroalgae" = Macro +`*EMA` + `ENMA_RUB`) %>%
  mutate("Turf" = `*TURFH` + `*TURFR` + `Turfsa` + `TurfsaR`) %>%
  mutate("Invertebrates"= Sponge + `OTH-SINV`) %>%
  mutate("Coral"= Hard + Soft) %>%
  rename("Sand"= MGSU) %>%
  rename("Unknown"=`*UNK`) %>%
  select(c(Atoll:Site.Transect.Quadrat), "CCA", "Macroalgae",
         "Turf", "Invertebrates", "Coral", "Sand", "Unknown")
  
dim(benthic_wide) #240 quadrats
  
  

#### LONG DF #####
benthic_long <- benthic_wide %>%
  pivot_longer(-c(Atoll:Site.Transect.Quadrat), names_to = "Label")
```


Summaries
```{r}

benthic_wide %>%
  summarize(across(c("CCA":"Sand"), mean))

benthic_wide %>%
  group_by(Site) %>%
  summarize(mean=mean(Coral))

```

# Plots
```{r}
# Plot relative abundance
benthic_long$Label <- factor(benthic_long$Label,
                           levels = c("CCA", "Macroalgae", 
                                      "Turf", "Coral", 
                                      "Invertebrates", "Sand", "Unknown"))


# Rename the sites
benthic_long$Site <- dplyr::recode(benthic_long$Site, 
                "Il Anglaise Seaward"= "Salomon seaward",
                "Il Poule Seaward" = "Peros Banhos seaward",
                "Il Anglaise Lagoon" = "Salomon lagoon",
                "Il Poule Lagoon" = "Peros Banhos lagoon")


# Make teh data have the same x axis as the other plots
benthic_long$Site <- factor(benthic_long$Site, 
                          levels=c("Middle Brother", "Nelson", 
                                   "Peros Banhos lagoon","Peros Banhos seaward", 
                                   "Salomon lagoon", "Salomon seaward", 
                                   "Il de rats", "Il Lubine"))

benthic_long$Atoll <- factor(benthic_long$Atoll, levels=c("Brothers", "Nelsons Island", "Peros Banhos", 
"Salomon", "Egmont"))

p_benthic.cover <- benthic_long %>% 
  group_by(Site, Label) %>%
  summarize(mean=mean(value))%>% # this gets rid of the white lines (same plot without it)
  ggplot(aes(x = Site, y = mean, fill = Label)) + 
  geom_bar(position = "fill", stat = "identity") +
  labs(x = "Site", y = "Relative Abundance", fill = "Label") +
theme_pubr(base_size=16) +
  scale_fill_manual(values = c("CCA" = "#e67388",
                                         "Macroalgae" = "#30802f",
                                         "Turf" = "#bdd54e",
                                         "Coral" = "#794a94",
                                         "Invertebrates" = "#5e5eff",
                                         "Sand" = "#ffda5e",
                               "Unknown"="grey"))+ 
  theme(axis.text.x=element_text(angle=45, hjust=1)) + 
  scale_x_discrete(labels=c("Il Lubine" = "Egmont- Ile Lubine",
                            "Il de rats" = "Egmont- Ile de rats"))
p_benthic.cover


ggsave(p_benthic.cover, file="../figures/benthic.cover.png",
       width=10, height=10)
```



```{r}

# Rename the sites
benthic_wide$Site <- dplyr::recode(benthic_wide$Site, 
                "Il Anglaise Seaward"= "Salomon seaward",
                "Il Poule Seaward" = "Peros Banhos seaward",
                "Il Anglaise Lagoon" = "Salomon lagoon",
                "Il Poule Lagoon" = "Peros Banhos lagoon")


# Make teh data have the same x axis as the other plots
benthic_wide$Site <- factor(benthic_wide$Site, 
                          levels=c("Middle Brother", "Nelson", 
                                   "Peros Banhos lagoon","Peros Banhos seaward", 
                                   "Salomon lagoon", "Salomon seaward", 
                                   "Il de rats", "Il Lubine"))

benthic_wide$Atoll <- factor(benthic_wide$Atoll, levels=c("Brothers", "Nelson", "Peros Banos", 
"Salomon", "Egmont"))


p_benthic.coral <- benthic_wide%>%
  group_by(Site) %>%
  mutate(Coral.mean= mean(Coral),
           Coral.SD = sd(Coral),
         Coral.SE = Coral.SD/sqrt(length(Coral))) %>%
  ggplot(aes(x=Site, y=Coral.mean, color=Atoll)) + 
  geom_point(size=6)+
  geom_errorbar(aes(ymin = Coral.mean - Coral.SD, 
                    ymax = Coral.mean + Coral.SD), 
                width=0.2) +
    theme_pubr(base_size = 16) +  
  theme(axis.text.x = element_text(angle = 90)) +
    theme(axis.text.x = element_blank())+
  ylab("Coral Percent Cover") +
  scale_color_manual(values= c("#440154FF","#3B528BFF","#21908CFF","#5DC863FF","#FDE725FF")) +
  guides(col = "none")

p_benthic.coral

save(p_benthic.coral, file="../data/coral.by.site.RData")

ggsave(p_benthic.coral, file="../figures/benthic.coral.png",
       width=10, height=10)
```


# Models
```{r}
# Combine data with fishes and shark data
unique(benthic_wide$Site)
unique(benthic_wide$Atoll)
unique(mean.shark.abundance.tiles$Region)
unique(fish.site.tiles.average$Tile.Site)
unique(herbivore.bites.site$Site)

test <- benthic_wide %>%
  mutate(Atoll = recode(Atoll, "Peros Banos" = "PerosBanhos")) %>%
    mutate(Atoll = recode(Atoll, "Nelson" = "Nelson's Island")) %>%
  mutate(Site =recode(Site, "Peros Banhos seaward" = "Peros Banhos Seaward")) %>%
    mutate(Site =recode(Site, "Peros Banhos lagoon" = "Peros Banhos Lagoon"))

grazing <- herbivore.bites.site %>%
  mutate(Site = recode(Site, "Il Anglaise Lagoon" = "Salomon lagoon")) %>%
  mutate(Site = recode(Site, "Il Anglaise Seaward" = "Salomon seaward")) %>%
  mutate(Site = recode(Site, "Il Poule Seaward" = "Peros Banhos Seaward")) 

model_data <- test %>%
  left_join(mean.shark.abundance.tiles, by=c('Atoll'='Region')) %>%
  left_join(fish.site.tiles.average, by = c("Site" = "Tile.Site")) %>%
  left_join(grazing, by= c("Site" = "Site") ) %>%
  select(-Atoll.y) %>%
  rename(Atoll = Atoll.x)
```

http://www.sthda.com/english/articles/39-regression-model-diagnostics/161-linear-regression-assumptions-and-diagnostics-in-r-essentials/#regression-assumptions
https://www.r-bloggers.com/2020/10/residual-plots-and-assumption-checking/

### Coral
Herbivore density
```{r}
library(lmerTest) # gives you a p-value from lmer

hist(model_data$Coral)
hist(model_data$Macroalgae)

ggplot(model_data, aes(x=Herbivores.avg, y=Coral)) + geom_point() + geom_smooth()

# Coral and herbivores
coral_mod <- lmerTest::lmer(Coral ~ Herbivores.avg + (1|Atoll) , data= model_data)
summary(coral_mod)        
performance::r2(coral_mod)


# Model Diagnostics
library(DHARMa)
simres <- simulateResiduals(coral_mod)
plot(simres) # issues

plot(coral_mod, type=c("p","smooth"), col.line=1) # residuals vs fitted (with line), seems mainly linear (this looks at linearity which is most important)
qqnorm(residuals(coral_mod)) # are the residuals normally distributed (meh-ish) but also this isn't that important
qqline(residuals(coral_mod))
plot(coral_mod,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1) # scale location plot (homoskedasticity), seems ok but not great

# So lets use robust standard errors that help deal with heteroskedasticity


library("clubSandwich")
library(lmerTest) # gives you a p-value from lmer

clubSandwich::coef_test(coral_mod, vcov = vcovCR(coral_mod, type = "CR2")) # CR2 has a small sample size correction
```


Fish Grazing
```{r}
# Remove PB lagoon because there is no grazing data
grazing_model_data <- model_data %>%
  filter(Site != "Peros Banhos Lagoon")


ggplot(grazing_model_data, aes(x=bites.per.min.grazeable.mean, y=Coral)) + geom_point() + geom_smooth()




# linear model 
coral_mod.graze <- lmerTest::lmer(Coral ~ bites.per.min.grazeable.mean + (1|Atoll) , data= grazing_model_data)
summary(coral_mod.graze)
performance::r2(coral_mod.graze)

# Model Diagnostics
library(DHARMa)
simres <- simulateResiduals(coral_mod.graze)
plot(simres) # issues

plot(coral_mod.graze, type=c("p","smooth"), col.line=1) # residuals vs fitted (with line)
qqnorm(residuals(coral_mod.graze)) # are the residuals normally distributed (meh-ish)
qqline(residuals(coral_mod.graze))
plot(coral_mod.graze,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1) # scale location plot (homoskedasticity), not great

# so lets apply a robust standard errors again




library("clubSandwich")
library(lmerTest) # gives you a p-value from lmer

clubSandwich::coef_test(coral_mod.graze, vcov = vcovCR(coral_mod.graze, type = "CR2")) # CR2 has a small sample size correction

```





## Macroalgae
```{r}
ggplot(model_data, aes(x=Herbivores.avg, y=Coral)) + geom_point() + geom_smooth()


# Macroalgae
algae_mod <- lmerTest::lmer(Macroalgae ~ Herbivores.avg + (1|Atoll), data= model_data)
summary(algae_mod) # higher herbivores is positively related to high algae cover (but this is barely significant) and our scatterplot doesn't really show a relationship
performance::r2(algae_mod)


# Model Fit
library(DHARMa)
simres <- simulateResiduals(algae_mod)
plot(simres) # issues

plot(algae_mod, type=c("p","smooth"), col.line=1) # residuals vs fitted (with line)
qqnorm(residuals(algae_mod)) # are the residuals normally distributed (meh-ish)
qqline(residuals(algae_mod))
plot(algae_mod,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1) # this looks ok? but the dharma one says hommogeneity is violated

# so lets apply robust errors again?



library("clubSandwich")
library(lmerTest) # gives you a p-value from lmer

clubSandwich::coef_test(algae_mod, vcov = vcovCR(algae_mod, type = "CR2")) # CR2 has a small sample size correction
# now its no longer significant
```







Grazing
```{r}
ggplot(grazing_model_data, aes(x=bites.per.min.grazeable.mean, y=Macroalgae)) + geom_point() + geom_smooth()

algae_mod_graze <- lmerTest::lmer(Macroalgae ~ bites.per.min.grazeable.mean + (1|Atoll), data= grazing_model_data) # singular

# Try without the random effect 
algae_mod_graze_lm <- lm(Macroalgae ~ bites.per.min.grazeable.mean, data= grazing_model_data) # works
summary(algae_mod_graze_lm) # higher herbivores bites is related to higher algae percent cover

# Model Diagnostics
plot(algae_mod_graze_lm) # seems good

```




